tutorial/encuestas/urls.py
from django.conf.urls import patterns, url
from encuestas import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<poll_id>\d+)/$', views.detail, name='details'),
	url(r'^(?P<poll_id>\d+)/resultados/$', views.resultados, name='resultados'),
	url(r'^(?P<poll_id>\d+)/votos/$', views.votos, name='votos'),
)

tutorial/tutorial/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tutorial.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^encuestas/', include('encuestas.urls',namespace="encuestas")),
    url(r'^admin/', include(admin.site.urls)),
)

tutorial/encuestas/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __unicode__(self):
		return	self.question

	def fue_recientemente_publicado(self):
		return	self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	
	fue_recientemente_publicado.admin_order_field = 'pub_date'
	fue_recientemente_publicado.short_description = 'Published recently?'
	fue_recientemente_publicado.boolean = True

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.choice_text

tutorial/encuestas/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from encuestas.models import Poll, Choice

# Create your views here.
def index(request):
	latest_poll_list = Poll.objects.order_by("-pub_date")[:5]
	#template = loader.get_template("encuestas/index.html")
	#output = ', '.join([p.question for p in latest_poll_list])
	context = {'latest_poll_list': latest_poll_list,}
	return render(request,'encuestas/index.html',context)

def detail(request, poll_id):
	poll = get_object_or_404(Poll, pk=poll_id)
	return render(request, 'encuestas/detalles.html', {'poll': poll})

def resultados(request, poll_id):
	poll = get_object_or_404(Poll, pk=poll_id)
	return render(request, 'encuestas/resultados.html', {'poll': poll})

def votos(request, poll_id):
	p=get_object_or_404(Poll,pk=poll_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request,'encuestas/detalles.html',{
			'poll':p,
			'error_message': "No has seleccionado ninguna alternativa.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('encuestas:resultados',args=(p.id,)))

tutorial/encuestas/templates/encuestas/detalles.html
<h1>{{ poll.question }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'encuestas:votos' poll.id %}" method="post">
	{% csrf_token %}
	{% for choice in poll.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
	{% endfor %}
<input type="submit" value="Vote" />
</form>

tutorial/encuestas/templates/encuestas/index.html
{% if latest_poll_list %}
<ul>
	{% for poll in latest_poll_list %}
	<li><a href="{% url 'encuestas:detalles' poll.id %}">{{ poll.question }}</a></li>
	{% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

tutorial/encuestas/templates/encuestas/resultados.html
<h1>{{ poll.question }}</h1>
<ul>
{% for choice in poll.choice_set.all %}
<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'encuestas:detalles' poll.id %}">Vote again?</a>